"""empty message

Revision ID: 411f5b9fba09
Revises: 4db890f51c10
Create Date: 2026-08-01 23:56:21.940567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411f5b9fba09'
down_revision: Union[str, Sequence[str], None] = '4db890f51c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'created_at')
    # ### end Alembic commands ###
