"""intial version

Revision ID: 625648342cb1
Revises: 
Create Date: 2026-07-17 04:49:15.503658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625648342cb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('prompt_token', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('response_token', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('total_token', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'total_token')
    op.drop_column('logs', 'response_token')
    op.drop_column('logs', 'prompt_token')
    # ### end Alembic commands ###
