"""empty message

Revision ID: c28344eaf2ef
Revises: 411f5b9fba09
Create Date: 2026-08-02 22:57:20.638082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime,UTC

# revision identifiers, used by Alembic.
revision: str = 'c28344eaf2ef'
down_revision: Union[str, Sequence[str], None] = '411f5b9fba09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(length=50), nullable=False))
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
