"""added column models id in logs replacing provider id

Revision ID: ec8854703628
Revises: f6143decf1ef
Create Date: 2026-07-24 18:51:54.293767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8854703628'
down_revision: Union[str, Sequence[str], None] = 'f6143decf1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('model_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_logs_model_id'), 'logs', ['model_id'], unique=False)
    op.create_foreign_key(None, 'logs', 'models', ['model_id'], ['model_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_index(op.f('ix_logs_model_id'), table_name='logs')
    op.drop_column('logs', 'model_id')
    # ### end Alembic commands ###
