"""added models tables and deleted few rows of projects

Revision ID: f6143decf1ef
Revises: 625648342cb1
Create Date: 2026-07-24 18:31:24.838554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6143decf1ef'
down_revision: Union[str, Sequence[str], None] = '625648342cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('global_rpm', sa.Integer(), nullable=False),
    sa.Column('global_rpd', sa.Integer(), nullable=False),
    sa.Column('global_tpm', sa.Integer(), nullable=False),
    sa.Column('global_tpd', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_index(op.f('ix_models_model_id'), 'models', ['model_id'], unique=False)
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    # Step 1: Add column as nullable (safe — no data changes)
    # op.add_column('logs', sa.Column('model_id', sa.Integer(), nullable=True))

    # # Step 2: Backfill existing rows with a sensible default
    # op.execute("UPDATE logs SET model_id = 1 WHERE model_id IS NULL")

    # # Step 3: Now that every row has a value, make it NOT NULL
    # op.alter_column('logs', 'model_id', nullable=False)

    op.drop_index(op.f('ix_logs_provider_id'), table_name='logs')
    # op.create_index(op.f('ix_logs_model_id'), 'logs', ['model_id'], unique=False)
    op.drop_constraint(op.f('logs_provider_id_fkey'), 'logs', type_='foreignkey')
    # op.create_foreign_key(None, 'logs', 'models', ['model_id'], ['model_id'])
    op.drop_column('logs', 'provider_id')
    op.add_column('projects', sa.Column('rpm', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('rpd', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('tpd', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('tpm', sa.Integer(), nullable=False))
    op.drop_column('projects', 'token_limit_day')
    op.drop_column('projects', 'rpm_limit')
    op.drop_column('projects', 'rpd_limit')
    op.drop_column('projects', 'token_limit_minute')
    op.drop_column('providers', 'global_rpd')
    op.drop_column('providers', 'global_rpm')
    op.drop_column('users', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filepath', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('providers', sa.Column('global_rpm', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('providers', sa.Column('global_rpd', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('token_limit_minute', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('rpd_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('rpm_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('token_limit_day', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'tpm')
    op.drop_column('projects', 'tpd')
    op.drop_column('projects', 'rpd')
    op.drop_column('projects', 'rpm')
    op.add_column('logs', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key(op.f('logs_provider_id_fkey'), 'logs', 'providers', ['provider_id'], ['provider_id'])
    op.drop_index(op.f('ix_logs_model_id'), table_name='logs')
    op.create_index(op.f('ix_logs_provider_id'), 'logs', ['provider_id'], unique=False)
    op.drop_column('logs', 'model_id')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_index(op.f('ix_models_model_id'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
